export const amethystTheme = {
    h1: "text-3xl font-bold mb-4 text-[#6d28d9] border-b-2 border-[#ddd6fe] pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-[#6d28d9] mt-5",
    h3: "text-xl font-bold mb-3 text-[#6d28d9] mt-4",
    h4: "text-lg font-bold mb-2 text-[#6d28d9] mt-4",
    h5: "text-base font-bold mb-2 text-[#6d28d9] mt-3",
    h6: "text-sm font-bold mb-2 text-[#6d28d9] uppercase mt-3",
    p: "text-base text-gray-800 mb-4 leading-relaxed",
    a: "text-[#7c3aed] font-medium hover:text-[#5b21b6] underline decoration-[#c4b5fd] underline-offset-4 transition-colors",
    strong: "font-bold text-[#4c1d95] bg-[#f5f3ff] px-1 rounded",
    em: "italic text-[#5b21b6]",
    del: "line-through text-gray-400 decoration-[#8b5cf6]",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-[#8b5cf6]",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-[#8b5cf6] font-medium text-[#6d28d9]",
    li: "text-gray-800 font-normal",
    blockquote: "border-l-4 border-[#8b5cf6] pl-4 py-1 mb-4 text-gray-700 italic bg-[#f5f3ff] rounded-r",
    hr: "my-8 border-t-2 border-[#ede9fe]",
    pre: "bg-slate-900 text-slate-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-[#ede9fe] text-[#5b21b6] px-1.5 py-0.5 rounded",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-[#f5f3ff]",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-[#ede9fe] text-[#5b21b6]",
    tbody: "divide-y divide-[#ede9fe]",
    tr: "hover:bg-[#f5f3ff] transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-[#ddd6fe]",
    td: "px-4 py-2 text-gray-800",
};