export const crimsonTheme = {
    h1: "text-3xl font-bold mb-4 text-[#be185d] border-b-2 border-[#fbcfe8] pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-[#be185d] mt-5",
    h3: "text-xl font-bold mb-3 text-[#be185d] mt-4",
    h4: "text-lg font-bold mb-2 text-[#be185d] mt-4",
    h5: "text-base font-bold mb-2 text-[#be185d] mt-3",
    h6: "text-sm font-bold mb-2 text-[#be185d] uppercase mt-3",
    p: "text-base text-gray-800 mb-4 leading-relaxed",
    a: "text-[#db2777] font-medium hover:text-[#9d174d] underline decoration-[#f9a8d4] underline-offset-4 transition-colors",
    strong: "font-bold text-[#831843] bg-[#fdf2f8] px-1 rounded",
    em: "italic text-[#9d174d]",
    del: "line-through text-gray-400 decoration-[#ec4899]",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-[#ec4899]",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-[#ec4899] font-medium text-[#be185d]",
    li: "text-gray-800 font-normal",
    blockquote: "border-l-4 border-[#ec4899] pl-4 py-1 mb-4 text-gray-700 italic bg-[#fdf2f8] rounded-r",
    hr: "my-8 border-t-2 border-[#fce7f3]",
    pre: "bg-slate-900 text-slate-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-[#fce7f3] text-[#9d174d] px-1.5 py-0.5 rounded",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-[#fdf2f8]",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-[#fce7f3] text-[#9d174d]",
    tbody: "divide-y divide-[#fce7f3]",
    tr: "hover:bg-[#fdf2f8] transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-[#fbcfe8]",
    td: "px-4 py-2 text-gray-800",
};