export const grayTheme = {
    h1: "text-3xl font-bold mb-4 text-gray-700 border-b-2 border-gray-200 pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-gray-700 mt-5",
    h3: "text-xl font-bold mb-3 text-gray-700 mt-4",
    h4: "text-lg font-bold mb-2 text-gray-700 mt-4",
    h5: "text-base font-bold mb-2 text-gray-700 mt-3",
    h6: "text-sm font-bold mb-2 text-gray-700 uppercase mt-3",
    p: "text-base text-gray-800 mb-4 leading-relaxed",
    a: "text-gray-600 font-medium hover:text-gray-800 underline decoration-gray-300 underline-offset-4 transition-colors",
    strong: "font-bold text-gray-900 bg-gray-100 px-1 rounded",
    em: "italic text-gray-800",
    del: "line-through text-gray-400 decoration-gray-500",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-gray-500",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-gray-500 font-medium text-gray-700",
    li: "text-gray-800 font-normal",
    blockquote: "border-l-4 border-gray-500 pl-4 py-1 mb-4 text-gray-700 italic bg-gray-50 rounded-r",
    hr: "my-8 border-t-2 border-gray-200",
    pre: "bg-gray-900 text-gray-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-gray-100",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-gray-100 text-gray-800",
    tbody: "divide-y divide-gray-100",
    tr: "hover:bg-gray-50 transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-gray-200",
    td: "px-4 py-2 text-gray-800",
};