export const lavenderTheme = {
    h1: "text-3xl font-bold mb-4 text-[#7e22ce] border-b-2 border-[#e9d5ff] pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-[#7e22ce] mt-5",
    h3: "text-xl font-bold mb-3 text-[#7e22ce] mt-4",
    h4: "text-lg font-bold mb-2 text-[#7e22ce] mt-4",
    h5: "text-base font-bold mb-2 text-[#7e22ce] mt-3",
    h6: "text-sm font-bold mb-2 text-[#7e22ce] uppercase mt-3",
    p: "text-base text-gray-800 mb-4 leading-relaxed",
    a: "text-[#9333ea] font-medium hover:text-[#6b21a8] underline decoration-[#d8b4fe] underline-offset-4 transition-colors",
    strong: "font-bold text-[#581c87] bg-[#faf5ff] px-1 rounded",
    em: "italic text-[#6b21a8]",
    del: "line-through text-gray-400 decoration-[#a855f7]",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-[#a855f7]",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-[#a855f7] font-medium text-[#7e22ce]",
    li: "text-gray-800 font-normal",
    blockquote: "border-l-4 border-[#a855f7] pl-4 py-1 mb-4 text-gray-700 italic bg-[#faf5ff] rounded-r",
    hr: "my-8 border-t-2 border-[#f3e8ff]",
    pre: "bg-slate-900 text-slate-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-[#f3e8ff] text-[#6b21a8] px-1.5 py-0.5 rounded",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-[#faf5ff]",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-[#f3e8ff] text-[#6b21a8]",
    tbody: "divide-y divide-[#f3e8ff]",
    tr: "hover:bg-[#faf5ff] transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-[#e9d5ff]",
    td: "px-4 py-2 text-gray-800",
};