export const neutralTheme = {
    h1: "text-3xl font-bold mb-4 text-neutral-700 border-b-2 border-neutral-200 pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-neutral-700 mt-5",
    h3: "text-xl font-bold mb-3 text-neutral-700 mt-4",
    h4: "text-lg font-bold mb-2 text-neutral-700 mt-4",
    h5: "text-base font-bold mb-2 text-neutral-700 mt-3",
    h6: "text-sm font-bold mb-2 text-neutral-700 uppercase mt-3",
    p: "text-base text-neutral-800 mb-4 leading-relaxed",
    a: "text-neutral-600 font-medium hover:text-neutral-800 underline decoration-neutral-300 underline-offset-4 transition-colors",
    strong: "font-bold text-neutral-900 bg-neutral-100 px-1 rounded",
    em: "italic text-neutral-800",
    del: "line-through text-neutral-400 decoration-neutral-500",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-neutral-500",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-neutral-500 font-medium text-neutral-700",
    li: "text-neutral-800 font-normal",
    blockquote: "border-l-4 border-neutral-500 pl-4 py-1 mb-4 text-neutral-700 italic bg-neutral-50 rounded-r",
    hr: "my-8 border-t-2 border-neutral-200",
    pre: "bg-neutral-900 text-neutral-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-neutral-100 text-neutral-800 px-1.5 py-0.5 rounded",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-neutral-100",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-neutral-100 text-neutral-800",
    tbody: "divide-y divide-neutral-100",
    tr: "hover:bg-neutral-50 transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-neutral-200",
    td: "px-4 py-2 text-neutral-800",
};