export const rubyTheme = {
    h1: "text-3xl font-bold mb-4 text-[#be123c] border-b-2 border-[#fecdd3] pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-[#be123c] mt-5",
    h3: "text-xl font-bold mb-3 text-[#be123c] mt-4",
    h4: "text-lg font-bold mb-2 text-[#be123c] mt-4",
    h5: "text-base font-bold mb-2 text-[#be123c] mt-3",
    h6: "text-sm font-bold mb-2 text-[#be123c] uppercase mt-3",
    p: "text-base text-gray-800 mb-4 leading-relaxed",
    a: "text-[#e11d48] font-medium hover:text-[#9f1239] underline decoration-[#fda4af] underline-offset-4 transition-colors",
    strong: "font-bold text-[#881337] bg-[#fff1f2] px-1 rounded",
    em: "italic text-[#9f1239]",
    del: "line-through text-gray-400 decoration-[#f43f5e]",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-[#f43f5e]",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-[#f43f5e] font-medium text-[#be123c]",
    li: "text-gray-800 font-normal",
    blockquote: "border-l-4 border-[#f43f5e] pl-4 py-1 mb-4 text-gray-700 italic bg-[#fff1f2] rounded-r",
    hr: "my-8 border-t-2 border-[#ffe4e6]",
    pre: "bg-slate-900 text-slate-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-[#ffe4e6] text-[#9f1239] px-1.5 py-0.5 rounded",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-[#fff1f2]",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-[#ffe4e6] text-[#9f1239]",
    tbody: "divide-y divide-[#ffe4e6]",
    tr: "hover:bg-[#fff1f2] transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-[#fecdd3]",
    td: "px-4 py-2 text-gray-800",
};