export const sapphireTheme = {
    h1: "text-3xl font-bold mb-4 text-[#1d4ed8] border-b-2 border-[#bfdbfe] pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-[#1d4ed8] mt-5",
    h3: "text-xl font-bold mb-3 text-[#1d4ed8] mt-4",
    h4: "text-lg font-bold mb-2 text-[#1d4ed8] mt-4",
    h5: "text-base font-bold mb-2 text-[#1d4ed8] mt-3",
    h6: "text-sm font-bold mb-2 text-[#1d4ed8] uppercase mt-3",
    p: "text-base text-gray-800 mb-4 leading-relaxed",
    a: "text-[#2563eb] font-medium hover:text-[#1e40af] underline decoration-[#93c5fd] underline-offset-4 transition-colors",
    strong: "font-bold text-[#1e3a8a] bg-[#eff6ff] px-1 rounded",
    em: "italic text-[#1e40af]",
    del: "line-through text-gray-400 decoration-[#3b82f6]",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-[#3b82f6]",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-[#3b82f6] font-medium text-[#1d4ed8]",
    li: "text-gray-800 font-normal",
    blockquote: "border-l-4 border-[#3b82f6] pl-4 py-1 mb-4 text-gray-700 italic bg-[#eff6ff] rounded-r",
    hr: "my-8 border-t-2 border-[#dbeafe]",
    pre: "bg-slate-900 text-slate-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-[#dbeafe] text-[#1e40af] px-1.5 py-0.5 rounded",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-[#eff6ff]",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-[#dbeafe] text-[#1e40af]",
    tbody: "divide-y divide-[#dbeafe]",
    tr: "hover:bg-[#eff6ff] transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-[#bfdbfe]",
    td: "px-4 py-2 text-gray-800",
};