export const stoneTheme = {
    h1: "text-3xl font-bold mb-4 text-stone-700 border-b-2 border-stone-200 pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-stone-700 mt-5",
    h3: "text-xl font-bold mb-3 text-stone-700 mt-4",
    h4: "text-lg font-bold mb-2 text-stone-700 mt-4",
    h5: "text-base font-bold mb-2 text-stone-700 mt-3",
    h6: "text-sm font-bold mb-2 text-stone-700 uppercase mt-3",
    p: "text-base text-stone-800 mb-4 leading-relaxed",
    a: "text-stone-600 font-medium hover:text-stone-800 underline decoration-stone-300 underline-offset-4 transition-colors",
    strong: "font-bold text-stone-900 bg-stone-100 px-1 rounded",
    em: "italic text-stone-800",
    del: "line-through text-stone-400 decoration-stone-500",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-stone-500",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-stone-500 font-medium text-stone-700",
    li: "text-stone-800 font-normal",
    blockquote: "border-l-4 border-stone-500 pl-4 py-1 mb-4 text-stone-700 italic bg-stone-50 rounded-r",
    hr: "my-8 border-t-2 border-stone-200",
    pre: "bg-stone-900 text-stone-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-stone-100 text-stone-800 px-1.5 py-0.5 rounded",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-stone-100",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-stone-100 text-stone-800",
    tbody: "divide-y divide-stone-100",
    tr: "hover:bg-stone-50 transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-stone-200",
    td: "px-4 py-2 text-stone-800",
};