export const yellowTheme = {
    h1: "text-3xl font-bold mb-4 text-yellow-700 border-b-2 border-yellow-300 pb-2 mt-6",
    h2: "text-2xl font-bold mb-3 text-yellow-700 mt-5",
    h3: "text-xl font-bold mb-3 text-yellow-700 mt-4",
    h4: "text-lg font-bold mb-2 text-yellow-700 mt-4",
    h5: "text-base font-bold mb-2 text-yellow-700 mt-3",
    h6: "text-sm font-bold mb-2 text-yellow-700 uppercase mt-3",
    p: "text-base text-gray-800 mb-4 leading-relaxed",
    a: "text-yellow-600 font-medium hover:text-yellow-800 underline decoration-yellow-400 underline-offset-4 transition-colors",
    strong: "font-bold text-yellow-900 bg-yellow-100 px-1 rounded",
    em: "italic text-yellow-800",
    del: "line-through text-gray-400 decoration-yellow-500",
    ul: "list-disc pl-6 mb-4 space-y-1 marker:text-yellow-500",
    ol: "list-decimal pl-6 mb-4 space-y-1 marker:text-yellow-500 font-medium text-yellow-700",
    li: "text-gray-800 font-normal",
    blockquote: "border-l-4 border-yellow-500 pl-4 py-1 mb-4 text-gray-700 italic bg-yellow-50 rounded-r",
    hr: "my-8 border-t-2 border-yellow-200",
    pre: "bg-slate-900 text-slate-50 p-4 rounded-lg overflow-x-auto mb-4",
    code: "font-mono text-sm bg-yellow-100 text-yellow-900 px-1.5 py-0.5 rounded border border-yellow-200",
    img: "rounded-lg shadow-md mb-4 max-w-full h-auto border-2 border-yellow-100",
    table: "w-full text-left border-collapse mb-4 rounded overflow-hidden",
    thead: "bg-yellow-100 text-yellow-900",
    tbody: "divide-y divide-yellow-100",
    tr: "hover:bg-yellow-50 transition-colors",
    th: "font-semibold px-4 py-2 border-b-2 border-yellow-300",
    td: "px-4 py-2 text-gray-800",
};